name: PvpLevels
version: 1.2.2
main: com.lenis0012.bukkit.pvp.PvpLevels
description: Better pvp in minecraft
author: lenis0012
commands:
  kdr:
    description: PvpLevels KDR command.
    usage: /kdr
  level:
    description: Change a player level.
    usage: /level <add/remove/set> <player> <amount>